"""Initial migration

Revision ID: 5be08bbc5d72
Revises:
Create Date: 2025-10-20 07:31:18.943865

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5be08bbc5d72"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create citext extension if it doesn't exist
    op.execute("CREATE EXTENSION IF NOT EXISTS citext;")

    op.create_table(
        "novena_days",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("day_number", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("day_number"),
        schema="parranda",
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("full_name", sa.Text(), nullable=True),
        sa.Column("alias", sa.Text(), nullable=True),
        sa.Column("phone", sa.Text(), nullable=True),
        sa.Column("password_hash", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("alias"),
        sa.UniqueConstraint("email"),
        schema="parranda",
    )
    op.create_table(
        "novena_day_sections",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("day_id", sa.UUID(), nullable=False),
        sa.Column("section_type", sa.String(length=20), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("content_md", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["day_id"],
            ["parranda.novena_days.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "day_id",
            "section_type",
            "position",
            name="novena_day_sections_day_id_section_type_position_key",
        ),
        schema="parranda",
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("session_token_hash", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["parranda.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_token_hash"),
        schema="parranda",
    )
    op.create_table(
        "user_novena_progress",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("day_id", sa.UUID(), nullable=False),
        sa.Column("is_completed", sa.Boolean(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_read_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["day_id"],
            ["parranda.novena_days.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["parranda.users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "day_id"),
        schema="parranda",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_novena_progress", schema="parranda")
    op.drop_table("sessions", schema="parranda")
    op.drop_table("novena_day_sections", schema="parranda")
    op.drop_table("users", schema="parranda")
    op.drop_table("novena_days", schema="parranda")
    # ### end Alembic commands ###
